name: Deploy Backend to AWS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  # First Job: Deploy to the Development Account
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials for Dev
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.DEV_AWS_ROLE_ARN }}
          aws-region: ${{ secrets.DEV_AWS_REGION }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Deploy to Dev
        run: npx cdk deploy --require-approval never

  # Second Job: Deploy to the Production Account
  deploy-prod:
    runs-on: ubuntu-latest
    # This job will only run if the 'deploy-dev' job succeeds
    needs: deploy-dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials for Prod
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.PROD_AWS_ROLE_ARN }}
          aws-region: ${{ secrets.PROD_AWS_REGION }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Deploy to Prod
        run: npx cdk deploy --require-approval never